### ISSUE TITLE
工欲善其事必先利其器

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#4]
### 小而强大的.exe文件
+ [ScreenToGif](https://screentogif.codeplex.com/)--屏幕录制软件，到官网上下载就是一个.exe文件，无需安装，操作简单。

+ [txt2Mobi通用版](http://vdisk.weibo.com/s/unOmAM4uwhgme?sudaref=www.baidu.com)--txt文件格式文件必须转换为mobi等格式才可以在kindle阅读，这个下载下来也是一个`.exe`文件，打开之后将`.txt`文件拖到软件，就会自动生成一个`.html`文件和`.mobi`文件，接下来只需要将`.mobi`文件拷贝到kindle的`.document`文件夹就可以直接阅读了。

+ [sdr-Cleaner_win](http://vdisk.weibo.com/s/AMW7KGSNOu5D)文件只有5.4M,也是一个`.exe`文件，数据线连接kindle和电脑，双击这个`.exe`文件就会自动清理kindle了。
+ [everything](http://www.voidtools.com/)电脑上的文件查找软件，非常强大，Windows64操作系统可以选择`Everything-1.4.0.713b.x64.Multilingual-Setup.exe`这个下载，安装之后文件也不是很大。

+ [微盘](http://vdisk.weibo.com/)上面的两个网站都是微盘的网站，的确微盘是一个找资源的好网站。

### 谷歌插件

谷歌浏览器的插件都需要通过谷歌应用商店添加，但是无奈的是需要翻墙，但是山人自有妙计，[谷歌插件网](http://chromecj.com/)就是一个国内的谷歌插件网站，这个网站上有很多强大的停不下来的插件，可以完美地解决添加插件的问题。下面是我正在用的插件
+ [Smart TOC](https://chrome.google.com/webstore/detail/smart-toc/lifgeihcfpkmmlfjbailfpfhbahhibba/related)
![](https://camo.githubusercontent.com/a402c76adf5d05a3c871949c458d8225fb8f8613/687474703a2f2f6f6f327239726e7a702e626b742e636c6f7564646e2e636f6d2f323031372d30342d303925323030332e33332e34352e676966)

+ [insight](https://chrome.google.com/webstore/detail/insightio-for-github/pmhfgjjhhomfplgmbalncpcohgeijonh)
给github换成IDE的风格

+ [adblock plus](http://chromecj.com/productivity/2014-07/24.html)chorme去广告插件，官网[https://adblockplus.org/zh_CN/]()，官网的缺点是不能成功下载，所以我的链接是直接到上面提及的谷歌插件网下载。这个插件可以屏蔽大多数广告，还可以自己手动右键屏蔽广告。

+ [花瓣网页采集工具](http://huaban.com/about/goodies/)，网页截图还可以编辑图片，快捷键`ctrl+ Shift+ R`还可以截取网页制作长图，还可以收集网页上好看的图片，花瓣网本身也是设计师的天堂。

+ [click && Clean](http://chromecj.com/productivity/2014-08/39/download.html) 一键删除浏览记录，以前只能通过`设置->历史记录—>清除浏览记录`才可以删除浏览记录，这样太消耗时间，现在用这个插件，实时显示浏览网页的个数，一键就可以删除，关闭浏览器自动清除浏览记录，如果遇到关闭重要的网页，还可以直接用谷歌自带快捷键`ctrl+ shift + T`，恢复刚刚关闭的网页。

+ [印象笔记·悦读](http://www.chromein.com/crx_5310.html)，自动识别博客主文，让阅读博客免受干扰，选择**本站**下载，就会自动添加到chorme插件上。

+ [Video Downloader [FVD]](http://www.chromein.com/crx_5363.html)网页视频自动检测，并下载，网页链接的图有点。。。但是下载不成问题，重要的是工具使用，很流畅地下载微博上的短视频。
---
以上是我在用的，小而功能强大的软件，如果你也有好的软件，非常欢迎一起分享，文章会持续更新！

**Comment by WangHuiying** [comment]
[谷歌输入工具](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab/related)
之前一直是在windows 下，现在换成linux的，搜狗输入法有时候会弹不出来，因此在知乎找到了这个浏览器插件

**Comment by WangHuiying** [comment]
https://insight.io
+ make github webpage as a IDE
+ view a file directly
+ download a single file instead of git clone a whole project
+ search keywords and show highlight result
+ jump to the reference or origin by press control in windows, I don't figure out why it is failed in mac.

+ related chrome extension:

---
![image](https://user-images.githubusercontent.com/18532655/32089452-a76ccd30-bb1c-11e7-88d7-95546b0e8de6.png)
![image](https://user-images.githubusercontent.com/18532655/32089454-a9a370a4-bb1c-11e7-9a1d-c954f06deac5.png)
![image](https://user-images.githubusercontent.com/18532655/32089460-b0e49168-bb1c-11e7-88d0-493d227d0ce3.png)
![image](https://user-images.githubusercontent.com/18532655/32089462-b52ae22c-bb1c-11e7-8624-c65ba57ef669.png)
